services:
  api1: &api
    image: joaovytor/rinha-2026-swift:v2
    platform: linux/amd64
    environment: &api_env
      IVF_NPROBE: "${IVF_NPROBE:-12}"
      IVF_INITIAL_NPROBE: "${IVF_INITIAL_NPROBE:-12}"
      IVF_ADAPTIVE_MIN_VOTES: "${IVF_ADAPTIVE_MIN_VOTES:-2}"
      IVF_ADAPTIVE_MAX_VOTES: "${IVF_ADAPTIVE_MAX_VOTES:-3}"
      IVFPQ_RERANK_CANDIDATES: "${IVFPQ_RERANK_CANDIDATES:-}"
      IVF_USE_BBOX: "${IVF_USE_BBOX:-0}"
      DEBUG_STATS: "${DEBUG_STATS:-0}"
      WARMUP_COUNT: "${WARMUP_COUNT:-50000}"
      SOCKET_PATH: "/sockets/api1.sock"
    volumes:
      - sockets:/sockets
    cpus: "0.35"
    mem_limit: "130MB"
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "130MB"

  api2:
    <<: *api
    environment:
      <<: *api_env
      SOCKET_PATH: "/sockets/api2.sock"
    volumes:
      - sockets:/sockets

  lb:
    image: haproxy:3.3-alpine
    user: "0:0"
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - sockets:/sockets
    depends_on:
      - api1
      - api2
    cpus: "0.30"
    mem_limit: "90MB"
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "90MB"

volumes:
  sockets:
